# Auto generated from NEAT_schema.yaml by pythongen.py version: 0.9.0
# Generation date: 2022-05-11T17:26:38
# Schema: NEAT_schema
#
# id: https://w3id.org/neat_schema
# description: A schema generated by LinkML for specifying graph ML pipelines in NEAT.
# license: https://fsf.org/

import dataclasses
import sys
import re
from jsonasobj2 import JsonObj, as_dict
from typing import Optional, List, Union, Dict, ClassVar, Any
from dataclasses import dataclass
from linkml_runtime.linkml_model.meta import EnumDefinition, PermissibleValue, PvFormulaOptions

from linkml_runtime.utils.slot import Slot
from linkml_runtime.utils.metamodelcore import empty_list, empty_dict, bnode
from linkml_runtime.utils.yamlutils import YAMLRoot, extended_str, extended_float, extended_int
from linkml_runtime.utils.dataclass_extensions_376 import dataclasses_init_fn_with_kwargs
from linkml_runtime.utils.formatutils import camelcase, underscore, sfx
from linkml_runtime.utils.enumerations import EnumDefinitionImpl
from rdflib import Namespace, URIRef
from linkml_runtime.utils.curienamespace import CurieNamespace
from linkml_runtime.linkml_model.types import Boolean, Float, Integer, String
from linkml_runtime.utils.metamodelcore import Bool

metamodel_version = "1.7.0"
version = None

# Overwrite dataclasses _init_fn to add **kwargs in __init__
dataclasses._init_fn = dataclasses_init_fn_with_kwargs

# Namespaces
LINKML = CurieNamespace('linkml', 'https://w3id.org/linkml/')
DEFAULT_ = CurieNamespace('', 'https://w3id.org/neat_schema/')


# Types

# Class references



@dataclass
class NeatConfiguration(YAMLRoot):
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/NeatConfiguration")
    class_class_curie: ClassVar[str] = None
    class_name: ClassVar[str] = "NeatConfiguration"
    class_model_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/NeatConfiguration")

    graph_data: Optional[Union[dict, "GraphDataConfiguration"]] = None

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self.graph_data is not None and not isinstance(self.graph_data, GraphDataConfiguration):
            self.graph_data = GraphDataConfiguration(**as_dict(self.graph_data))

        super().__post_init__(**kwargs)


@dataclass
class GraphDataConfiguration(YAMLRoot):
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/GraphDataConfiguration")
    class_class_curie: ClassVar[str] = None
    class_name: ClassVar[str] = "GraphDataConfiguration"
    class_model_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/GraphDataConfiguration")

    graph: Optional[Union[dict, "EnsmallenRunConfig"]] = None
    data: Optional[Union[dict, "TrainValidData"]] = None

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self.graph is not None and not isinstance(self.graph, EnsmallenRunConfig):
            self.graph = EnsmallenRunConfig(**as_dict(self.graph))

        if self.data is not None and not isinstance(self.data, TrainValidData):
            self.data = TrainValidData(**as_dict(self.data))

        super().__post_init__(**kwargs)


@dataclass
class TrainValidData(YAMLRoot):
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/TrainValidData")
    class_class_curie: ClassVar[str] = None
    class_name: ClassVar[str] = "TrainValidData"
    class_model_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/TrainValidData")

    train_data: Optional[Union[dict, "PosNegData"]] = None
    valid_data: Optional[Union[dict, "PosNegData"]] = None

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self.train_data is not None and not isinstance(self.train_data, PosNegData):
            self.train_data = PosNegData(**as_dict(self.train_data))

        if self.valid_data is not None and not isinstance(self.valid_data, PosNegData):
            self.valid_data = PosNegData(**as_dict(self.valid_data))

        super().__post_init__(**kwargs)


@dataclass
class PosNegData(YAMLRoot):
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/PosNegData")
    class_class_curie: ClassVar[str] = None
    class_name: ClassVar[str] = "PosNegData"
    class_model_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/PosNegData")

    pos_edge_filepath: Optional[str] = None
    neg_edge_filepath: Optional[str] = None

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self.pos_edge_filepath is not None and not isinstance(self.pos_edge_filepath, str):
            self.pos_edge_filepath = str(self.pos_edge_filepath)

        if self.neg_edge_filepath is not None and not isinstance(self.neg_edge_filepath, str):
            self.neg_edge_filepath = str(self.neg_edge_filepath)

        super().__post_init__(**kwargs)


@dataclass
class EmbeddingsConfig(YAMLRoot):
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/EmbeddingsConfig")
    class_class_curie: ClassVar[str] = None
    class_name: ClassVar[str] = "EmbeddingsConfig"
    class_model_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/EmbeddingsConfig")

    filename: Optional[str] = None
    history_filename: Optional[str] = None
    node_embeddings_params: Optional[Union[dict, "NodeEmbeddingsParamsConfig"]] = None
    tsne_filename: Optional[str] = None

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self.filename is not None and not isinstance(self.filename, str):
            self.filename = str(self.filename)

        if self.history_filename is not None and not isinstance(self.history_filename, str):
            self.history_filename = str(self.history_filename)

        if self.node_embeddings_params is not None and not isinstance(self.node_embeddings_params, NodeEmbeddingsParamsConfig):
            self.node_embeddings_params = NodeEmbeddingsParamsConfig(**as_dict(self.node_embeddings_params))

        if self.tsne_filename is not None and not isinstance(self.tsne_filename, str):
            self.tsne_filename = str(self.tsne_filename)

        super().__post_init__(**kwargs)


@dataclass
class NodeEmbeddingsParamsConfig(YAMLRoot):
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/NodeEmbeddingsParamsConfig")
    class_class_curie: ClassVar[str] = None
    class_name: ClassVar[str] = "NodeEmbeddingsParamsConfig"
    class_model_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/NodeEmbeddingsParamsConfig")

    method_name: Optional[Union[str, "NodeEmbedMethodEnum"]] = None
    walk_length: Optional[int] = None
    batch_size: Optional[int] = None
    window_size: Optional[int] = None
    return_weight: Optional[float] = None
    explore_weight: Optional[float] = None
    iterations: Optional[int] = None

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self.method_name is not None and not isinstance(self.method_name, NodeEmbedMethodEnum):
            self.method_name = NodeEmbedMethodEnum(self.method_name)

        if self.walk_length is not None and not isinstance(self.walk_length, int):
            self.walk_length = int(self.walk_length)

        if self.batch_size is not None and not isinstance(self.batch_size, int):
            self.batch_size = int(self.batch_size)

        if self.window_size is not None and not isinstance(self.window_size, int):
            self.window_size = int(self.window_size)

        if self.return_weight is not None and not isinstance(self.return_weight, float):
            self.return_weight = float(self.return_weight)

        if self.explore_weight is not None and not isinstance(self.explore_weight, float):
            self.explore_weight = float(self.explore_weight)

        if self.iterations is not None and not isinstance(self.iterations, int):
            self.iterations = int(self.iterations)

        super().__post_init__(**kwargs)


@dataclass
class ClassifierContainer(YAMLRoot):
    """
    A container with multiple classifiers in it.
    """
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/ClassifierContainer")
    class_class_curie: ClassVar[str] = None
    class_name: ClassVar[str] = "ClassifierContainer"
    class_model_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/ClassifierContainer")

    classifiers: Optional[Union[Union[dict, "Classifier"], List[Union[dict, "Classifier"]]]] = empty_list()

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if not isinstance(self.classifiers, list):
            self.classifiers = [self.classifiers] if self.classifiers is not None else []
        self.classifiers = [v if isinstance(v, Classifier) else Classifier(**as_dict(v)) for v in self.classifiers]

        super().__post_init__(**kwargs)


@dataclass
class Classifier(YAMLRoot):
    """
    ML classifiers to be trained-tested-validated and applied for predictions.
    """
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/Classifier")
    class_class_curie: ClassVar[str] = None
    class_name: ClassVar[str] = "Classifier"
    class_model_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/Classifier")

    classifier_id: Optional[str] = None
    classifier_name: Optional[str] = None
    classifier_type: Optional[str] = None
    edge_method: Optional[Union[str, "EdgeMethodEnum"]] = None
    outfile: Optional[str] = None
    parameters: Optional[Union[dict, "ClassifierParams"]] = None

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self.classifier_id is not None and not isinstance(self.classifier_id, str):
            self.classifier_id = str(self.classifier_id)

        if self.classifier_name is not None and not isinstance(self.classifier_name, str):
            self.classifier_name = str(self.classifier_name)

        if self.classifier_type is not None and not isinstance(self.classifier_type, str):
            self.classifier_type = str(self.classifier_type)

        if self.edge_method is not None and not isinstance(self.edge_method, EdgeMethodEnum):
            self.edge_method = EdgeMethodEnum(self.edge_method)

        if self.outfile is not None and not isinstance(self.outfile, str):
            self.outfile = str(self.outfile)

        if self.parameters is not None and not isinstance(self.parameters, ClassifierParams):
            self.parameters = ClassifierParams(**as_dict(self.parameters))

        super().__post_init__(**kwargs)


@dataclass
class ClassifierParams(YAMLRoot):
    """
    Parameters needed to define a classifier.
    """
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/ClassifierParams")
    class_class_curie: ClassVar[str] = None
    class_name: ClassVar[str] = "ClassifierParams"
    class_model_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/ClassifierParams")

    random_state: Optional[int] = None
    max_iter: Optional[int] = None

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self.random_state is not None and not isinstance(self.random_state, int):
            self.random_state = int(self.random_state)

        if self.max_iter is not None and not isinstance(self.max_iter, int):
            self.max_iter = int(self.max_iter)

        super().__post_init__(**kwargs)


@dataclass
class ApplyTrainedModelsContainer(YAMLRoot):
    """
    A container with multiple classifiers in it.
    """
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/ApplyTrainedModelsContainer")
    class_class_curie: ClassVar[str] = None
    class_name: ClassVar[str] = "ApplyTrainedModelsContainer"
    class_model_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/ApplyTrainedModelsContainer")

    models: Optional[Union[Union[dict, "ApplyTrainedModel"], List[Union[dict, "ApplyTrainedModel"]]]] = empty_list()

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if not isinstance(self.models, list):
            self.models = [self.models] if self.models is not None else []
        self.models = [v if isinstance(v, ApplyTrainedModel) else ApplyTrainedModel(**as_dict(v)) for v in self.models]

        super().__post_init__(**kwargs)


@dataclass
class ApplyTrainedModel(YAMLRoot):
    """
    Trained model used for prediction.
    """
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/ApplyTrainedModel")
    class_class_curie: ClassVar[str] = None
    class_name: ClassVar[str] = "ApplyTrainedModel"
    class_model_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/ApplyTrainedModel")

    model_id: Optional[str] = None
    node_types: Optional[Union[dict, "NodeType"]] = None
    cutoff: Optional[str] = None
    outfile: Optional[str] = None

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self.model_id is not None and not isinstance(self.model_id, str):
            self.model_id = str(self.model_id)

        if self.node_types is not None and not isinstance(self.node_types, NodeType):
            self.node_types = NodeType(**as_dict(self.node_types))

        if self.cutoff is not None and not isinstance(self.cutoff, str):
            self.cutoff = str(self.cutoff)

        if self.outfile is not None and not isinstance(self.outfile, str):
            self.outfile = str(self.outfile)

        super().__post_init__(**kwargs)


@dataclass
class NodeType(YAMLRoot):
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/NodeType")
    class_class_curie: ClassVar[str] = None
    class_name: ClassVar[str] = "NodeType"
    class_model_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/NodeType")

    source: Optional[Union[str, List[str]]] = empty_list()
    destination: Optional[Union[str, List[str]]] = empty_list()

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if not isinstance(self.source, list):
            self.source = [self.source] if self.source is not None else []
        self.source = [v if isinstance(v, str) else str(v) for v in self.source]

        if not isinstance(self.destination, list):
            self.destination = [self.destination] if self.destination is not None else []
        self.destination = [v if isinstance(v, str) else str(v) for v in self.destination]

        super().__post_init__(**kwargs)


@dataclass
class Upload(YAMLRoot):
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/Upload")
    class_class_curie: ClassVar[str] = None
    class_name: ClassVar[str] = "Upload"
    class_model_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/Upload")

    s3_bucket: Optional[str] = None
    s3_bucket_dir: Optional[str] = None
    extra_args: Optional[Union[str, List[str]]] = empty_list()

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self.s3_bucket is not None and not isinstance(self.s3_bucket, str):
            self.s3_bucket = str(self.s3_bucket)

        if self.s3_bucket_dir is not None and not isinstance(self.s3_bucket_dir, str):
            self.s3_bucket_dir = str(self.s3_bucket_dir)

        if not isinstance(self.extra_args, list):
            self.extra_args = [self.extra_args] if self.extra_args is not None else []
        self.extra_args = [v if isinstance(v, str) else str(v) for v in self.extra_args]

        super().__post_init__(**kwargs)


@dataclass
class Target(YAMLRoot):
    """
    Path for output to be saved.
    """
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/Target")
    class_class_curie: ClassVar[str] = None
    class_name: ClassVar[str] = "Target"
    class_model_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/Target")

    target_path: Optional[str] = None

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self.target_path is not None and not isinstance(self.target_path, str):
            self.target_path = str(self.target_path)

        super().__post_init__(**kwargs)


@dataclass
class EnsmallenRunConfig(YAMLRoot):
    """
    All params used by ensmallen's csv_reader
    """
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/EnsmallenRunConfig")
    class_class_curie: ClassVar[str] = None
    class_name: ClassVar[str] = "EnsmallenRunConfig"
    class_model_uri: ClassVar[URIRef] = URIRef("https://w3id.org/neat_schema/EnsmallenRunConfig")

    node_type_path: Optional[str] = None
    node_type_list_separator: Optional[str] = None
    node_types_column_number: Optional[int] = None
    node_types_column: Optional[str] = None
    node_types_ids_column_number: Optional[int] = None
    node_types_ids_column: Optional[str] = None
    node_types_number: Optional[int] = None
    numeric_node_type_ids: Optional[Union[bool, Bool]] = None
    minimum_node_type_id: Optional[int] = None
    node_type_list_header: Optional[Union[bool, Bool]] = None
    node_type_list_rows_to_skip: Optional[int] = None
    node_type_list_is_correct: Optional[Union[bool, Bool]] = None
    node_type_list_max_rows_number: Optional[int] = None
    node_type_list_comment_symbol: Optional[str] = None
    load_node_type_list_in_parallel: Optional[Union[bool, Bool]] = None
    node_path: Optional[str] = None
    node_list_separator: Optional[str] = None
    node_list_header: Optional[Union[bool, Bool]] = None
    node_list_rows_to_skip: Optional[int] = None
    node_list_is_correct: Optional[Union[bool, Bool]] = None
    node_list_max_rows_number: Optional[int] = None
    node_list_comment_symbol: Optional[str] = None
    default_node_type: Optional[str] = None
    nodes_column_number: Optional[int] = None
    nodes_column: Optional[str] = None
    node_types_separator: Optional[str] = None
    node_list_node_types_column_number: Optional[int] = None
    node_list_node_types_column: Optional[str] = None
    node_ids_column: Optional[str] = None
    node_ids_column_number: Optional[int] = None
    nodes_number: Optional[int] = None
    minimum_node_id: Optional[int] = None
    numeric_node_ids: Optional[Union[bool, Bool]] = None
    node_list_numeric_node_type_ids: Optional[Union[bool, Bool]] = None
    skip_node_types_if_unavailable: Optional[Union[bool, Bool]] = None
    load_node_list_in_parallel: Optional[Union[bool, Bool]] = None
    edge_type_path: Optional[str] = None
    edge_types_column_number: Optional[int] = None
    edge_types_column: Optional[str] = None
    edge_types_ids_column_number: Optional[int] = None
    edge_types_ids_column: Optional[str] = None
    edge_types_number: Optional[int] = None
    numeric_edge_type_ids: Optional[Union[bool, Bool]] = None
    minimum_edge_type_id: Optional[int] = None
    edge_type_list_separator: Optional[str] = None
    edge_type_list_header: Optional[Union[bool, Bool]] = None
    edge_type_list_rows_to_skip: Optional[int] = None
    edge_type_list_is_correct: Optional[Union[bool, Bool]] = None
    edge_type_list_max_rows_number: Optional[int] = None
    edge_type_list_comment_symbol: Optional[str] = None
    load_edge_type_list_in_parallel: Optional[Union[bool, Bool]] = None
    edge_path: Optional[str] = None
    edge_list_separator: Optional[str] = None
    edge_list_header: Optional[Union[bool, Bool]] = None
    edge_list_rows_to_skip: Optional[int] = None
    sources_column_number: Optional[int] = None
    sources_column: Optional[str] = None
    destinations_column_number: Optional[int] = None
    destinations_column: Optional[str] = None
    edge_list_edge_types_column_number: Optional[int] = None
    edge_list_edge_types_column: Optional[str] = None
    default_edge_type: Optional[str] = None
    weights_column_number: Optional[int] = None
    weights_column: Optional[str] = None
    default_weight: Optional[float] = None
    edge_ids_column: Optional[str] = None
    edge_ids_column_number: Optional[int] = None
    edge_list_numeric_edge_type_ids: Optional[Union[bool, Bool]] = None
    edge_list_numeric_node_ids: Optional[Union[bool, Bool]] = None
    skip_weights_if_unavailable: Optional[Union[bool, Bool]] = None
    skip_edge_types_if_unavailable: Optional[Union[bool, Bool]] = None
    edge_list_is_complete: Optional[Union[bool, Bool]] = None
    edge_list_may_contain_duplicates: Optional[Union[bool, Bool]] = None
    edge_list_is_sorted: Optional[Union[bool, Bool]] = None
    edge_list_is_correct: Optional[Union[bool, Bool]] = None
    edge_list_max_rows_number: Optional[int] = None
    edge_list_comment_symbol: Optional[str] = None
    edges_number: Optional[int] = None
    load_edge_list_in_parallel: Optional[Union[bool, Bool]] = None
    verbose: Optional[Union[bool, Bool]] = None
    may_have_singletons: Optional[Union[bool, Bool]] = None
    may_have_singleton_with_selfloops: Optional[Union[bool, Bool]] = None
    directed: Optional[Union[bool, Bool]] = None
    name: Optional[str] = None

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self.node_type_path is not None and not isinstance(self.node_type_path, str):
            self.node_type_path = str(self.node_type_path)

        if self.node_type_list_separator is not None and not isinstance(self.node_type_list_separator, str):
            self.node_type_list_separator = str(self.node_type_list_separator)

        if self.node_types_column_number is not None and not isinstance(self.node_types_column_number, int):
            self.node_types_column_number = int(self.node_types_column_number)

        if self.node_types_column is not None and not isinstance(self.node_types_column, str):
            self.node_types_column = str(self.node_types_column)

        if self.node_types_ids_column_number is not None and not isinstance(self.node_types_ids_column_number, int):
            self.node_types_ids_column_number = int(self.node_types_ids_column_number)

        if self.node_types_ids_column is not None and not isinstance(self.node_types_ids_column, str):
            self.node_types_ids_column = str(self.node_types_ids_column)

        if self.node_types_number is not None and not isinstance(self.node_types_number, int):
            self.node_types_number = int(self.node_types_number)

        if self.numeric_node_type_ids is not None and not isinstance(self.numeric_node_type_ids, Bool):
            self.numeric_node_type_ids = Bool(self.numeric_node_type_ids)

        if self.minimum_node_type_id is not None and not isinstance(self.minimum_node_type_id, int):
            self.minimum_node_type_id = int(self.minimum_node_type_id)

        if self.node_type_list_header is not None and not isinstance(self.node_type_list_header, Bool):
            self.node_type_list_header = Bool(self.node_type_list_header)

        if self.node_type_list_rows_to_skip is not None and not isinstance(self.node_type_list_rows_to_skip, int):
            self.node_type_list_rows_to_skip = int(self.node_type_list_rows_to_skip)

        if self.node_type_list_is_correct is not None and not isinstance(self.node_type_list_is_correct, Bool):
            self.node_type_list_is_correct = Bool(self.node_type_list_is_correct)

        if self.node_type_list_max_rows_number is not None and not isinstance(self.node_type_list_max_rows_number, int):
            self.node_type_list_max_rows_number = int(self.node_type_list_max_rows_number)

        if self.node_type_list_comment_symbol is not None and not isinstance(self.node_type_list_comment_symbol, str):
            self.node_type_list_comment_symbol = str(self.node_type_list_comment_symbol)

        if self.load_node_type_list_in_parallel is not None and not isinstance(self.load_node_type_list_in_parallel, Bool):
            self.load_node_type_list_in_parallel = Bool(self.load_node_type_list_in_parallel)

        if self.node_path is not None and not isinstance(self.node_path, str):
            self.node_path = str(self.node_path)

        if self.node_list_separator is not None and not isinstance(self.node_list_separator, str):
            self.node_list_separator = str(self.node_list_separator)

        if self.node_list_header is not None and not isinstance(self.node_list_header, Bool):
            self.node_list_header = Bool(self.node_list_header)

        if self.node_list_rows_to_skip is not None and not isinstance(self.node_list_rows_to_skip, int):
            self.node_list_rows_to_skip = int(self.node_list_rows_to_skip)

        if self.node_list_is_correct is not None and not isinstance(self.node_list_is_correct, Bool):
            self.node_list_is_correct = Bool(self.node_list_is_correct)

        if self.node_list_max_rows_number is not None and not isinstance(self.node_list_max_rows_number, int):
            self.node_list_max_rows_number = int(self.node_list_max_rows_number)

        if self.node_list_comment_symbol is not None and not isinstance(self.node_list_comment_symbol, str):
            self.node_list_comment_symbol = str(self.node_list_comment_symbol)

        if self.default_node_type is not None and not isinstance(self.default_node_type, str):
            self.default_node_type = str(self.default_node_type)

        if self.nodes_column_number is not None and not isinstance(self.nodes_column_number, int):
            self.nodes_column_number = int(self.nodes_column_number)

        if self.nodes_column is not None and not isinstance(self.nodes_column, str):
            self.nodes_column = str(self.nodes_column)

        if self.node_types_separator is not None and not isinstance(self.node_types_separator, str):
            self.node_types_separator = str(self.node_types_separator)

        if self.node_list_node_types_column_number is not None and not isinstance(self.node_list_node_types_column_number, int):
            self.node_list_node_types_column_number = int(self.node_list_node_types_column_number)

        if self.node_list_node_types_column is not None and not isinstance(self.node_list_node_types_column, str):
            self.node_list_node_types_column = str(self.node_list_node_types_column)

        if self.node_ids_column is not None and not isinstance(self.node_ids_column, str):
            self.node_ids_column = str(self.node_ids_column)

        if self.node_ids_column_number is not None and not isinstance(self.node_ids_column_number, int):
            self.node_ids_column_number = int(self.node_ids_column_number)

        if self.nodes_number is not None and not isinstance(self.nodes_number, int):
            self.nodes_number = int(self.nodes_number)

        if self.minimum_node_id is not None and not isinstance(self.minimum_node_id, int):
            self.minimum_node_id = int(self.minimum_node_id)

        if self.numeric_node_ids is not None and not isinstance(self.numeric_node_ids, Bool):
            self.numeric_node_ids = Bool(self.numeric_node_ids)

        if self.node_list_numeric_node_type_ids is not None and not isinstance(self.node_list_numeric_node_type_ids, Bool):
            self.node_list_numeric_node_type_ids = Bool(self.node_list_numeric_node_type_ids)

        if self.skip_node_types_if_unavailable is not None and not isinstance(self.skip_node_types_if_unavailable, Bool):
            self.skip_node_types_if_unavailable = Bool(self.skip_node_types_if_unavailable)

        if self.load_node_list_in_parallel is not None and not isinstance(self.load_node_list_in_parallel, Bool):
            self.load_node_list_in_parallel = Bool(self.load_node_list_in_parallel)

        if self.edge_type_path is not None and not isinstance(self.edge_type_path, str):
            self.edge_type_path = str(self.edge_type_path)

        if self.edge_types_column_number is not None and not isinstance(self.edge_types_column_number, int):
            self.edge_types_column_number = int(self.edge_types_column_number)

        if self.edge_types_column is not None and not isinstance(self.edge_types_column, str):
            self.edge_types_column = str(self.edge_types_column)

        if self.edge_types_ids_column_number is not None and not isinstance(self.edge_types_ids_column_number, int):
            self.edge_types_ids_column_number = int(self.edge_types_ids_column_number)

        if self.edge_types_ids_column is not None and not isinstance(self.edge_types_ids_column, str):
            self.edge_types_ids_column = str(self.edge_types_ids_column)

        if self.edge_types_number is not None and not isinstance(self.edge_types_number, int):
            self.edge_types_number = int(self.edge_types_number)

        if self.numeric_edge_type_ids is not None and not isinstance(self.numeric_edge_type_ids, Bool):
            self.numeric_edge_type_ids = Bool(self.numeric_edge_type_ids)

        if self.minimum_edge_type_id is not None and not isinstance(self.minimum_edge_type_id, int):
            self.minimum_edge_type_id = int(self.minimum_edge_type_id)

        if self.edge_type_list_separator is not None and not isinstance(self.edge_type_list_separator, str):
            self.edge_type_list_separator = str(self.edge_type_list_separator)

        if self.edge_type_list_header is not None and not isinstance(self.edge_type_list_header, Bool):
            self.edge_type_list_header = Bool(self.edge_type_list_header)

        if self.edge_type_list_rows_to_skip is not None and not isinstance(self.edge_type_list_rows_to_skip, int):
            self.edge_type_list_rows_to_skip = int(self.edge_type_list_rows_to_skip)

        if self.edge_type_list_is_correct is not None and not isinstance(self.edge_type_list_is_correct, Bool):
            self.edge_type_list_is_correct = Bool(self.edge_type_list_is_correct)

        if self.edge_type_list_max_rows_number is not None and not isinstance(self.edge_type_list_max_rows_number, int):
            self.edge_type_list_max_rows_number = int(self.edge_type_list_max_rows_number)

        if self.edge_type_list_comment_symbol is not None and not isinstance(self.edge_type_list_comment_symbol, str):
            self.edge_type_list_comment_symbol = str(self.edge_type_list_comment_symbol)

        if self.load_edge_type_list_in_parallel is not None and not isinstance(self.load_edge_type_list_in_parallel, Bool):
            self.load_edge_type_list_in_parallel = Bool(self.load_edge_type_list_in_parallel)

        if self.edge_path is not None and not isinstance(self.edge_path, str):
            self.edge_path = str(self.edge_path)

        if self.edge_list_separator is not None and not isinstance(self.edge_list_separator, str):
            self.edge_list_separator = str(self.edge_list_separator)

        if self.edge_list_header is not None and not isinstance(self.edge_list_header, Bool):
            self.edge_list_header = Bool(self.edge_list_header)

        if self.edge_list_rows_to_skip is not None and not isinstance(self.edge_list_rows_to_skip, int):
            self.edge_list_rows_to_skip = int(self.edge_list_rows_to_skip)

        if self.sources_column_number is not None and not isinstance(self.sources_column_number, int):
            self.sources_column_number = int(self.sources_column_number)

        if self.sources_column is not None and not isinstance(self.sources_column, str):
            self.sources_column = str(self.sources_column)

        if self.destinations_column_number is not None and not isinstance(self.destinations_column_number, int):
            self.destinations_column_number = int(self.destinations_column_number)

        if self.destinations_column is not None and not isinstance(self.destinations_column, str):
            self.destinations_column = str(self.destinations_column)

        if self.edge_list_edge_types_column_number is not None and not isinstance(self.edge_list_edge_types_column_number, int):
            self.edge_list_edge_types_column_number = int(self.edge_list_edge_types_column_number)

        if self.edge_list_edge_types_column is not None and not isinstance(self.edge_list_edge_types_column, str):
            self.edge_list_edge_types_column = str(self.edge_list_edge_types_column)

        if self.default_edge_type is not None and not isinstance(self.default_edge_type, str):
            self.default_edge_type = str(self.default_edge_type)

        if self.weights_column_number is not None and not isinstance(self.weights_column_number, int):
            self.weights_column_number = int(self.weights_column_number)

        if self.weights_column is not None and not isinstance(self.weights_column, str):
            self.weights_column = str(self.weights_column)

        if self.default_weight is not None and not isinstance(self.default_weight, float):
            self.default_weight = float(self.default_weight)

        if self.edge_ids_column is not None and not isinstance(self.edge_ids_column, str):
            self.edge_ids_column = str(self.edge_ids_column)

        if self.edge_ids_column_number is not None and not isinstance(self.edge_ids_column_number, int):
            self.edge_ids_column_number = int(self.edge_ids_column_number)

        if self.edge_list_numeric_edge_type_ids is not None and not isinstance(self.edge_list_numeric_edge_type_ids, Bool):
            self.edge_list_numeric_edge_type_ids = Bool(self.edge_list_numeric_edge_type_ids)

        if self.edge_list_numeric_node_ids is not None and not isinstance(self.edge_list_numeric_node_ids, Bool):
            self.edge_list_numeric_node_ids = Bool(self.edge_list_numeric_node_ids)

        if self.skip_weights_if_unavailable is not None and not isinstance(self.skip_weights_if_unavailable, Bool):
            self.skip_weights_if_unavailable = Bool(self.skip_weights_if_unavailable)

        if self.skip_edge_types_if_unavailable is not None and not isinstance(self.skip_edge_types_if_unavailable, Bool):
            self.skip_edge_types_if_unavailable = Bool(self.skip_edge_types_if_unavailable)

        if self.edge_list_is_complete is not None and not isinstance(self.edge_list_is_complete, Bool):
            self.edge_list_is_complete = Bool(self.edge_list_is_complete)

        if self.edge_list_may_contain_duplicates is not None and not isinstance(self.edge_list_may_contain_duplicates, Bool):
            self.edge_list_may_contain_duplicates = Bool(self.edge_list_may_contain_duplicates)

        if self.edge_list_is_sorted is not None and not isinstance(self.edge_list_is_sorted, Bool):
            self.edge_list_is_sorted = Bool(self.edge_list_is_sorted)

        if self.edge_list_is_correct is not None and not isinstance(self.edge_list_is_correct, Bool):
            self.edge_list_is_correct = Bool(self.edge_list_is_correct)

        if self.edge_list_max_rows_number is not None and not isinstance(self.edge_list_max_rows_number, int):
            self.edge_list_max_rows_number = int(self.edge_list_max_rows_number)

        if self.edge_list_comment_symbol is not None and not isinstance(self.edge_list_comment_symbol, str):
            self.edge_list_comment_symbol = str(self.edge_list_comment_symbol)

        if self.edges_number is not None and not isinstance(self.edges_number, int):
            self.edges_number = int(self.edges_number)

        if self.load_edge_list_in_parallel is not None and not isinstance(self.load_edge_list_in_parallel, Bool):
            self.load_edge_list_in_parallel = Bool(self.load_edge_list_in_parallel)

        if self.verbose is not None and not isinstance(self.verbose, Bool):
            self.verbose = Bool(self.verbose)

        if self.may_have_singletons is not None and not isinstance(self.may_have_singletons, Bool):
            self.may_have_singletons = Bool(self.may_have_singletons)

        if self.may_have_singleton_with_selfloops is not None and not isinstance(self.may_have_singleton_with_selfloops, Bool):
            self.may_have_singleton_with_selfloops = Bool(self.may_have_singleton_with_selfloops)

        if self.directed is not None and not isinstance(self.directed, Bool):
            self.directed = Bool(self.directed)

        if self.name is not None and not isinstance(self.name, str):
            self.name = str(self.name)

        super().__post_init__(**kwargs)


# Enumerations
class NodeEmbedMethodEnum(EnumDefinitionImpl):

    SkipGram = PermissibleValue(text="SkipGram")
    CBOW = PermissibleValue(text="CBOW")
    GloVe = PermissibleValue(text="GloVe")
    Siamese = PermissibleValue(text="Siamese")
    TransE = PermissibleValue(text="TransE")
    SimplE = PermissibleValue(text="SimplE")
    TransH = PermissibleValue(text="TransH")
    TransR = PermissibleValue(text="TransR")

    _defn = EnumDefinition(
        name="NodeEmbedMethodEnum",
    )

class EdgeMethodEnum(EnumDefinitionImpl):

    Average = PermissibleValue(text="Average")
    Hadamard = PermissibleValue(text="Hadamard")
    Sum = PermissibleValue(text="Sum")
    L1 = PermissibleValue(text="L1")
    L2 = PermissibleValue(text="L2")
    AbsoluteL1 = PermissibleValue(text="AbsoluteL1")

    _defn = EnumDefinition(
        name="EdgeMethodEnum",
    )

# Slots
class slots:
    pass

slots.neatConfiguration__graph_data = Slot(uri=DEFAULT_.graph_data, name="neatConfiguration__graph_data", curie=DEFAULT_.curie('graph_data'),
                   model_uri=DEFAULT_.neatConfiguration__graph_data, domain=None, range=Optional[Union[dict, GraphDataConfiguration]])

slots.graphDataConfiguration__graph = Slot(uri=DEFAULT_.graph, name="graphDataConfiguration__graph", curie=DEFAULT_.curie('graph'),
                   model_uri=DEFAULT_.graphDataConfiguration__graph, domain=None, range=Optional[Union[dict, EnsmallenRunConfig]])

slots.graphDataConfiguration__data = Slot(uri=DEFAULT_.data, name="graphDataConfiguration__data", curie=DEFAULT_.curie('data'),
                   model_uri=DEFAULT_.graphDataConfiguration__data, domain=None, range=Optional[Union[dict, TrainValidData]])

slots.trainValidData__train_data = Slot(uri=DEFAULT_.train_data, name="trainValidData__train_data", curie=DEFAULT_.curie('train_data'),
                   model_uri=DEFAULT_.trainValidData__train_data, domain=None, range=Optional[Union[dict, PosNegData]])

slots.trainValidData__valid_data = Slot(uri=DEFAULT_.valid_data, name="trainValidData__valid_data", curie=DEFAULT_.curie('valid_data'),
                   model_uri=DEFAULT_.trainValidData__valid_data, domain=None, range=Optional[Union[dict, PosNegData]])

slots.posNegData__pos_edge_filepath = Slot(uri=DEFAULT_.pos_edge_filepath, name="posNegData__pos_edge_filepath", curie=DEFAULT_.curie('pos_edge_filepath'),
                   model_uri=DEFAULT_.posNegData__pos_edge_filepath, domain=None, range=Optional[str])

slots.posNegData__neg_edge_filepath = Slot(uri=DEFAULT_.neg_edge_filepath, name="posNegData__neg_edge_filepath", curie=DEFAULT_.curie('neg_edge_filepath'),
                   model_uri=DEFAULT_.posNegData__neg_edge_filepath, domain=None, range=Optional[str])

slots.embeddingsConfig__filename = Slot(uri=DEFAULT_.filename, name="embeddingsConfig__filename", curie=DEFAULT_.curie('filename'),
                   model_uri=DEFAULT_.embeddingsConfig__filename, domain=None, range=Optional[str])

slots.embeddingsConfig__history_filename = Slot(uri=DEFAULT_.history_filename, name="embeddingsConfig__history_filename", curie=DEFAULT_.curie('history_filename'),
                   model_uri=DEFAULT_.embeddingsConfig__history_filename, domain=None, range=Optional[str])

slots.embeddingsConfig__node_embeddings_params = Slot(uri=DEFAULT_.node_embeddings_params, name="embeddingsConfig__node_embeddings_params", curie=DEFAULT_.curie('node_embeddings_params'),
                   model_uri=DEFAULT_.embeddingsConfig__node_embeddings_params, domain=None, range=Optional[Union[dict, NodeEmbeddingsParamsConfig]])

slots.embeddingsConfig__tsne_filename = Slot(uri=DEFAULT_.tsne_filename, name="embeddingsConfig__tsne_filename", curie=DEFAULT_.curie('tsne_filename'),
                   model_uri=DEFAULT_.embeddingsConfig__tsne_filename, domain=None, range=Optional[str])

slots.nodeEmbeddingsParamsConfig__method_name = Slot(uri=DEFAULT_.method_name, name="nodeEmbeddingsParamsConfig__method_name", curie=DEFAULT_.curie('method_name'),
                   model_uri=DEFAULT_.nodeEmbeddingsParamsConfig__method_name, domain=None, range=Optional[Union[str, "NodeEmbedMethodEnum"]])

slots.nodeEmbeddingsParamsConfig__walk_length = Slot(uri=DEFAULT_.walk_length, name="nodeEmbeddingsParamsConfig__walk_length", curie=DEFAULT_.curie('walk_length'),
                   model_uri=DEFAULT_.nodeEmbeddingsParamsConfig__walk_length, domain=None, range=Optional[int])

slots.nodeEmbeddingsParamsConfig__batch_size = Slot(uri=DEFAULT_.batch_size, name="nodeEmbeddingsParamsConfig__batch_size", curie=DEFAULT_.curie('batch_size'),
                   model_uri=DEFAULT_.nodeEmbeddingsParamsConfig__batch_size, domain=None, range=Optional[int])

slots.nodeEmbeddingsParamsConfig__window_size = Slot(uri=DEFAULT_.window_size, name="nodeEmbeddingsParamsConfig__window_size", curie=DEFAULT_.curie('window_size'),
                   model_uri=DEFAULT_.nodeEmbeddingsParamsConfig__window_size, domain=None, range=Optional[int])

slots.nodeEmbeddingsParamsConfig__return_weight = Slot(uri=DEFAULT_.return_weight, name="nodeEmbeddingsParamsConfig__return_weight", curie=DEFAULT_.curie('return_weight'),
                   model_uri=DEFAULT_.nodeEmbeddingsParamsConfig__return_weight, domain=None, range=Optional[float])

slots.nodeEmbeddingsParamsConfig__explore_weight = Slot(uri=DEFAULT_.explore_weight, name="nodeEmbeddingsParamsConfig__explore_weight", curie=DEFAULT_.curie('explore_weight'),
                   model_uri=DEFAULT_.nodeEmbeddingsParamsConfig__explore_weight, domain=None, range=Optional[float])

slots.nodeEmbeddingsParamsConfig__iterations = Slot(uri=DEFAULT_.iterations, name="nodeEmbeddingsParamsConfig__iterations", curie=DEFAULT_.curie('iterations'),
                   model_uri=DEFAULT_.nodeEmbeddingsParamsConfig__iterations, domain=None, range=Optional[int])

slots.classifierContainer__classifiers = Slot(uri=DEFAULT_.classifiers, name="classifierContainer__classifiers", curie=DEFAULT_.curie('classifiers'),
                   model_uri=DEFAULT_.classifierContainer__classifiers, domain=None, range=Optional[Union[Union[dict, Classifier], List[Union[dict, Classifier]]]])

slots.classifier__classifier_id = Slot(uri=DEFAULT_.classifier_id, name="classifier__classifier_id", curie=DEFAULT_.curie('classifier_id'),
                   model_uri=DEFAULT_.classifier__classifier_id, domain=None, range=Optional[str])

slots.classifier__classifier_name = Slot(uri=DEFAULT_.classifier_name, name="classifier__classifier_name", curie=DEFAULT_.curie('classifier_name'),
                   model_uri=DEFAULT_.classifier__classifier_name, domain=None, range=Optional[str])

slots.classifier__classifier_type = Slot(uri=DEFAULT_.classifier_type, name="classifier__classifier_type", curie=DEFAULT_.curie('classifier_type'),
                   model_uri=DEFAULT_.classifier__classifier_type, domain=None, range=Optional[str])

slots.classifier__edge_method = Slot(uri=DEFAULT_.edge_method, name="classifier__edge_method", curie=DEFAULT_.curie('edge_method'),
                   model_uri=DEFAULT_.classifier__edge_method, domain=None, range=Optional[Union[str, "EdgeMethodEnum"]])

slots.classifier__outfile = Slot(uri=DEFAULT_.outfile, name="classifier__outfile", curie=DEFAULT_.curie('outfile'),
                   model_uri=DEFAULT_.classifier__outfile, domain=None, range=Optional[str])

slots.classifier__parameters = Slot(uri=DEFAULT_.parameters, name="classifier__parameters", curie=DEFAULT_.curie('parameters'),
                   model_uri=DEFAULT_.classifier__parameters, domain=None, range=Optional[Union[dict, ClassifierParams]])

slots.classifierParams__random_state = Slot(uri=DEFAULT_.random_state, name="classifierParams__random_state", curie=DEFAULT_.curie('random_state'),
                   model_uri=DEFAULT_.classifierParams__random_state, domain=None, range=Optional[int])

slots.classifierParams__max_iter = Slot(uri=DEFAULT_.max_iter, name="classifierParams__max_iter", curie=DEFAULT_.curie('max_iter'),
                   model_uri=DEFAULT_.classifierParams__max_iter, domain=None, range=Optional[int])

slots.applyTrainedModelsContainer__models = Slot(uri=DEFAULT_.models, name="applyTrainedModelsContainer__models", curie=DEFAULT_.curie('models'),
                   model_uri=DEFAULT_.applyTrainedModelsContainer__models, domain=None, range=Optional[Union[Union[dict, ApplyTrainedModel], List[Union[dict, ApplyTrainedModel]]]])

slots.applyTrainedModel__model_id = Slot(uri=DEFAULT_.model_id, name="applyTrainedModel__model_id", curie=DEFAULT_.curie('model_id'),
                   model_uri=DEFAULT_.applyTrainedModel__model_id, domain=None, range=Optional[str])

slots.applyTrainedModel__node_types = Slot(uri=DEFAULT_.node_types, name="applyTrainedModel__node_types", curie=DEFAULT_.curie('node_types'),
                   model_uri=DEFAULT_.applyTrainedModel__node_types, domain=None, range=Optional[Union[dict, NodeType]])

slots.applyTrainedModel__cutoff = Slot(uri=DEFAULT_.cutoff, name="applyTrainedModel__cutoff", curie=DEFAULT_.curie('cutoff'),
                   model_uri=DEFAULT_.applyTrainedModel__cutoff, domain=None, range=Optional[str])

slots.applyTrainedModel__outfile = Slot(uri=DEFAULT_.outfile, name="applyTrainedModel__outfile", curie=DEFAULT_.curie('outfile'),
                   model_uri=DEFAULT_.applyTrainedModel__outfile, domain=None, range=Optional[str])

slots.nodeType__source = Slot(uri=DEFAULT_.source, name="nodeType__source", curie=DEFAULT_.curie('source'),
                   model_uri=DEFAULT_.nodeType__source, domain=None, range=Optional[Union[str, List[str]]])

slots.nodeType__destination = Slot(uri=DEFAULT_.destination, name="nodeType__destination", curie=DEFAULT_.curie('destination'),
                   model_uri=DEFAULT_.nodeType__destination, domain=None, range=Optional[Union[str, List[str]]])

slots.upload__s3_bucket = Slot(uri=DEFAULT_.s3_bucket, name="upload__s3_bucket", curie=DEFAULT_.curie('s3_bucket'),
                   model_uri=DEFAULT_.upload__s3_bucket, domain=None, range=Optional[str])

slots.upload__s3_bucket_dir = Slot(uri=DEFAULT_.s3_bucket_dir, name="upload__s3_bucket_dir", curie=DEFAULT_.curie('s3_bucket_dir'),
                   model_uri=DEFAULT_.upload__s3_bucket_dir, domain=None, range=Optional[str])

slots.upload__extra_args = Slot(uri=DEFAULT_.extra_args, name="upload__extra_args", curie=DEFAULT_.curie('extra_args'),
                   model_uri=DEFAULT_.upload__extra_args, domain=None, range=Optional[Union[str, List[str]]])

slots.target__target_path = Slot(uri=DEFAULT_.target_path, name="target__target_path", curie=DEFAULT_.curie('target_path'),
                   model_uri=DEFAULT_.target__target_path, domain=None, range=Optional[str])

slots.ensmallenRunConfig__node_type_path = Slot(uri=DEFAULT_.node_type_path, name="ensmallenRunConfig__node_type_path", curie=DEFAULT_.curie('node_type_path'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_type_path, domain=None, range=Optional[str])

slots.ensmallenRunConfig__node_type_list_separator = Slot(uri=DEFAULT_.node_type_list_separator, name="ensmallenRunConfig__node_type_list_separator", curie=DEFAULT_.curie('node_type_list_separator'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_type_list_separator, domain=None, range=Optional[str])

slots.ensmallenRunConfig__node_types_column_number = Slot(uri=DEFAULT_.node_types_column_number, name="ensmallenRunConfig__node_types_column_number", curie=DEFAULT_.curie('node_types_column_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_types_column_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__node_types_column = Slot(uri=DEFAULT_.node_types_column, name="ensmallenRunConfig__node_types_column", curie=DEFAULT_.curie('node_types_column'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_types_column, domain=None, range=Optional[str])

slots.ensmallenRunConfig__node_types_ids_column_number = Slot(uri=DEFAULT_.node_types_ids_column_number, name="ensmallenRunConfig__node_types_ids_column_number", curie=DEFAULT_.curie('node_types_ids_column_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_types_ids_column_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__node_types_ids_column = Slot(uri=DEFAULT_.node_types_ids_column, name="ensmallenRunConfig__node_types_ids_column", curie=DEFAULT_.curie('node_types_ids_column'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_types_ids_column, domain=None, range=Optional[str])

slots.ensmallenRunConfig__node_types_number = Slot(uri=DEFAULT_.node_types_number, name="ensmallenRunConfig__node_types_number", curie=DEFAULT_.curie('node_types_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_types_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__numeric_node_type_ids = Slot(uri=DEFAULT_.numeric_node_type_ids, name="ensmallenRunConfig__numeric_node_type_ids", curie=DEFAULT_.curie('numeric_node_type_ids'),
                   model_uri=DEFAULT_.ensmallenRunConfig__numeric_node_type_ids, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__minimum_node_type_id = Slot(uri=DEFAULT_.minimum_node_type_id, name="ensmallenRunConfig__minimum_node_type_id", curie=DEFAULT_.curie('minimum_node_type_id'),
                   model_uri=DEFAULT_.ensmallenRunConfig__minimum_node_type_id, domain=None, range=Optional[int])

slots.ensmallenRunConfig__node_type_list_header = Slot(uri=DEFAULT_.node_type_list_header, name="ensmallenRunConfig__node_type_list_header", curie=DEFAULT_.curie('node_type_list_header'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_type_list_header, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__node_type_list_rows_to_skip = Slot(uri=DEFAULT_.node_type_list_rows_to_skip, name="ensmallenRunConfig__node_type_list_rows_to_skip", curie=DEFAULT_.curie('node_type_list_rows_to_skip'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_type_list_rows_to_skip, domain=None, range=Optional[int])

slots.ensmallenRunConfig__node_type_list_is_correct = Slot(uri=DEFAULT_.node_type_list_is_correct, name="ensmallenRunConfig__node_type_list_is_correct", curie=DEFAULT_.curie('node_type_list_is_correct'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_type_list_is_correct, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__node_type_list_max_rows_number = Slot(uri=DEFAULT_.node_type_list_max_rows_number, name="ensmallenRunConfig__node_type_list_max_rows_number", curie=DEFAULT_.curie('node_type_list_max_rows_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_type_list_max_rows_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__node_type_list_comment_symbol = Slot(uri=DEFAULT_.node_type_list_comment_symbol, name="ensmallenRunConfig__node_type_list_comment_symbol", curie=DEFAULT_.curie('node_type_list_comment_symbol'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_type_list_comment_symbol, domain=None, range=Optional[str])

slots.ensmallenRunConfig__load_node_type_list_in_parallel = Slot(uri=DEFAULT_.load_node_type_list_in_parallel, name="ensmallenRunConfig__load_node_type_list_in_parallel", curie=DEFAULT_.curie('load_node_type_list_in_parallel'),
                   model_uri=DEFAULT_.ensmallenRunConfig__load_node_type_list_in_parallel, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__node_path = Slot(uri=DEFAULT_.node_path, name="ensmallenRunConfig__node_path", curie=DEFAULT_.curie('node_path'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_path, domain=None, range=Optional[str])

slots.ensmallenRunConfig__node_list_separator = Slot(uri=DEFAULT_.node_list_separator, name="ensmallenRunConfig__node_list_separator", curie=DEFAULT_.curie('node_list_separator'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_list_separator, domain=None, range=Optional[str])

slots.ensmallenRunConfig__node_list_header = Slot(uri=DEFAULT_.node_list_header, name="ensmallenRunConfig__node_list_header", curie=DEFAULT_.curie('node_list_header'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_list_header, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__node_list_rows_to_skip = Slot(uri=DEFAULT_.node_list_rows_to_skip, name="ensmallenRunConfig__node_list_rows_to_skip", curie=DEFAULT_.curie('node_list_rows_to_skip'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_list_rows_to_skip, domain=None, range=Optional[int])

slots.ensmallenRunConfig__node_list_is_correct = Slot(uri=DEFAULT_.node_list_is_correct, name="ensmallenRunConfig__node_list_is_correct", curie=DEFAULT_.curie('node_list_is_correct'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_list_is_correct, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__node_list_max_rows_number = Slot(uri=DEFAULT_.node_list_max_rows_number, name="ensmallenRunConfig__node_list_max_rows_number", curie=DEFAULT_.curie('node_list_max_rows_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_list_max_rows_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__node_list_comment_symbol = Slot(uri=DEFAULT_.node_list_comment_symbol, name="ensmallenRunConfig__node_list_comment_symbol", curie=DEFAULT_.curie('node_list_comment_symbol'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_list_comment_symbol, domain=None, range=Optional[str])

slots.ensmallenRunConfig__default_node_type = Slot(uri=DEFAULT_.default_node_type, name="ensmallenRunConfig__default_node_type", curie=DEFAULT_.curie('default_node_type'),
                   model_uri=DEFAULT_.ensmallenRunConfig__default_node_type, domain=None, range=Optional[str])

slots.ensmallenRunConfig__nodes_column_number = Slot(uri=DEFAULT_.nodes_column_number, name="ensmallenRunConfig__nodes_column_number", curie=DEFAULT_.curie('nodes_column_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__nodes_column_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__nodes_column = Slot(uri=DEFAULT_.nodes_column, name="ensmallenRunConfig__nodes_column", curie=DEFAULT_.curie('nodes_column'),
                   model_uri=DEFAULT_.ensmallenRunConfig__nodes_column, domain=None, range=Optional[str])

slots.ensmallenRunConfig__node_types_separator = Slot(uri=DEFAULT_.node_types_separator, name="ensmallenRunConfig__node_types_separator", curie=DEFAULT_.curie('node_types_separator'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_types_separator, domain=None, range=Optional[str])

slots.ensmallenRunConfig__node_list_node_types_column_number = Slot(uri=DEFAULT_.node_list_node_types_column_number, name="ensmallenRunConfig__node_list_node_types_column_number", curie=DEFAULT_.curie('node_list_node_types_column_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_list_node_types_column_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__node_list_node_types_column = Slot(uri=DEFAULT_.node_list_node_types_column, name="ensmallenRunConfig__node_list_node_types_column", curie=DEFAULT_.curie('node_list_node_types_column'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_list_node_types_column, domain=None, range=Optional[str])

slots.ensmallenRunConfig__node_ids_column = Slot(uri=DEFAULT_.node_ids_column, name="ensmallenRunConfig__node_ids_column", curie=DEFAULT_.curie('node_ids_column'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_ids_column, domain=None, range=Optional[str])

slots.ensmallenRunConfig__node_ids_column_number = Slot(uri=DEFAULT_.node_ids_column_number, name="ensmallenRunConfig__node_ids_column_number", curie=DEFAULT_.curie('node_ids_column_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_ids_column_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__nodes_number = Slot(uri=DEFAULT_.nodes_number, name="ensmallenRunConfig__nodes_number", curie=DEFAULT_.curie('nodes_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__nodes_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__minimum_node_id = Slot(uri=DEFAULT_.minimum_node_id, name="ensmallenRunConfig__minimum_node_id", curie=DEFAULT_.curie('minimum_node_id'),
                   model_uri=DEFAULT_.ensmallenRunConfig__minimum_node_id, domain=None, range=Optional[int])

slots.ensmallenRunConfig__numeric_node_ids = Slot(uri=DEFAULT_.numeric_node_ids, name="ensmallenRunConfig__numeric_node_ids", curie=DEFAULT_.curie('numeric_node_ids'),
                   model_uri=DEFAULT_.ensmallenRunConfig__numeric_node_ids, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__node_list_numeric_node_type_ids = Slot(uri=DEFAULT_.node_list_numeric_node_type_ids, name="ensmallenRunConfig__node_list_numeric_node_type_ids", curie=DEFAULT_.curie('node_list_numeric_node_type_ids'),
                   model_uri=DEFAULT_.ensmallenRunConfig__node_list_numeric_node_type_ids, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__skip_node_types_if_unavailable = Slot(uri=DEFAULT_.skip_node_types_if_unavailable, name="ensmallenRunConfig__skip_node_types_if_unavailable", curie=DEFAULT_.curie('skip_node_types_if_unavailable'),
                   model_uri=DEFAULT_.ensmallenRunConfig__skip_node_types_if_unavailable, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__load_node_list_in_parallel = Slot(uri=DEFAULT_.load_node_list_in_parallel, name="ensmallenRunConfig__load_node_list_in_parallel", curie=DEFAULT_.curie('load_node_list_in_parallel'),
                   model_uri=DEFAULT_.ensmallenRunConfig__load_node_list_in_parallel, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__edge_type_path = Slot(uri=DEFAULT_.edge_type_path, name="ensmallenRunConfig__edge_type_path", curie=DEFAULT_.curie('edge_type_path'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_type_path, domain=None, range=Optional[str])

slots.ensmallenRunConfig__edge_types_column_number = Slot(uri=DEFAULT_.edge_types_column_number, name="ensmallenRunConfig__edge_types_column_number", curie=DEFAULT_.curie('edge_types_column_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_types_column_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__edge_types_column = Slot(uri=DEFAULT_.edge_types_column, name="ensmallenRunConfig__edge_types_column", curie=DEFAULT_.curie('edge_types_column'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_types_column, domain=None, range=Optional[str])

slots.ensmallenRunConfig__edge_types_ids_column_number = Slot(uri=DEFAULT_.edge_types_ids_column_number, name="ensmallenRunConfig__edge_types_ids_column_number", curie=DEFAULT_.curie('edge_types_ids_column_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_types_ids_column_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__edge_types_ids_column = Slot(uri=DEFAULT_.edge_types_ids_column, name="ensmallenRunConfig__edge_types_ids_column", curie=DEFAULT_.curie('edge_types_ids_column'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_types_ids_column, domain=None, range=Optional[str])

slots.ensmallenRunConfig__edge_types_number = Slot(uri=DEFAULT_.edge_types_number, name="ensmallenRunConfig__edge_types_number", curie=DEFAULT_.curie('edge_types_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_types_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__numeric_edge_type_ids = Slot(uri=DEFAULT_.numeric_edge_type_ids, name="ensmallenRunConfig__numeric_edge_type_ids", curie=DEFAULT_.curie('numeric_edge_type_ids'),
                   model_uri=DEFAULT_.ensmallenRunConfig__numeric_edge_type_ids, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__minimum_edge_type_id = Slot(uri=DEFAULT_.minimum_edge_type_id, name="ensmallenRunConfig__minimum_edge_type_id", curie=DEFAULT_.curie('minimum_edge_type_id'),
                   model_uri=DEFAULT_.ensmallenRunConfig__minimum_edge_type_id, domain=None, range=Optional[int])

slots.ensmallenRunConfig__edge_type_list_separator = Slot(uri=DEFAULT_.edge_type_list_separator, name="ensmallenRunConfig__edge_type_list_separator", curie=DEFAULT_.curie('edge_type_list_separator'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_type_list_separator, domain=None, range=Optional[str])

slots.ensmallenRunConfig__edge_type_list_header = Slot(uri=DEFAULT_.edge_type_list_header, name="ensmallenRunConfig__edge_type_list_header", curie=DEFAULT_.curie('edge_type_list_header'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_type_list_header, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__edge_type_list_rows_to_skip = Slot(uri=DEFAULT_.edge_type_list_rows_to_skip, name="ensmallenRunConfig__edge_type_list_rows_to_skip", curie=DEFAULT_.curie('edge_type_list_rows_to_skip'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_type_list_rows_to_skip, domain=None, range=Optional[int])

slots.ensmallenRunConfig__edge_type_list_is_correct = Slot(uri=DEFAULT_.edge_type_list_is_correct, name="ensmallenRunConfig__edge_type_list_is_correct", curie=DEFAULT_.curie('edge_type_list_is_correct'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_type_list_is_correct, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__edge_type_list_max_rows_number = Slot(uri=DEFAULT_.edge_type_list_max_rows_number, name="ensmallenRunConfig__edge_type_list_max_rows_number", curie=DEFAULT_.curie('edge_type_list_max_rows_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_type_list_max_rows_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__edge_type_list_comment_symbol = Slot(uri=DEFAULT_.edge_type_list_comment_symbol, name="ensmallenRunConfig__edge_type_list_comment_symbol", curie=DEFAULT_.curie('edge_type_list_comment_symbol'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_type_list_comment_symbol, domain=None, range=Optional[str])

slots.ensmallenRunConfig__load_edge_type_list_in_parallel = Slot(uri=DEFAULT_.load_edge_type_list_in_parallel, name="ensmallenRunConfig__load_edge_type_list_in_parallel", curie=DEFAULT_.curie('load_edge_type_list_in_parallel'),
                   model_uri=DEFAULT_.ensmallenRunConfig__load_edge_type_list_in_parallel, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__edge_path = Slot(uri=DEFAULT_.edge_path, name="ensmallenRunConfig__edge_path", curie=DEFAULT_.curie('edge_path'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_path, domain=None, range=Optional[str])

slots.ensmallenRunConfig__edge_list_separator = Slot(uri=DEFAULT_.edge_list_separator, name="ensmallenRunConfig__edge_list_separator", curie=DEFAULT_.curie('edge_list_separator'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_list_separator, domain=None, range=Optional[str])

slots.ensmallenRunConfig__edge_list_header = Slot(uri=DEFAULT_.edge_list_header, name="ensmallenRunConfig__edge_list_header", curie=DEFAULT_.curie('edge_list_header'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_list_header, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__edge_list_rows_to_skip = Slot(uri=DEFAULT_.edge_list_rows_to_skip, name="ensmallenRunConfig__edge_list_rows_to_skip", curie=DEFAULT_.curie('edge_list_rows_to_skip'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_list_rows_to_skip, domain=None, range=Optional[int])

slots.ensmallenRunConfig__sources_column_number = Slot(uri=DEFAULT_.sources_column_number, name="ensmallenRunConfig__sources_column_number", curie=DEFAULT_.curie('sources_column_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__sources_column_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__sources_column = Slot(uri=DEFAULT_.sources_column, name="ensmallenRunConfig__sources_column", curie=DEFAULT_.curie('sources_column'),
                   model_uri=DEFAULT_.ensmallenRunConfig__sources_column, domain=None, range=Optional[str])

slots.ensmallenRunConfig__destinations_column_number = Slot(uri=DEFAULT_.destinations_column_number, name="ensmallenRunConfig__destinations_column_number", curie=DEFAULT_.curie('destinations_column_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__destinations_column_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__destinations_column = Slot(uri=DEFAULT_.destinations_column, name="ensmallenRunConfig__destinations_column", curie=DEFAULT_.curie('destinations_column'),
                   model_uri=DEFAULT_.ensmallenRunConfig__destinations_column, domain=None, range=Optional[str])

slots.ensmallenRunConfig__edge_list_edge_types_column_number = Slot(uri=DEFAULT_.edge_list_edge_types_column_number, name="ensmallenRunConfig__edge_list_edge_types_column_number", curie=DEFAULT_.curie('edge_list_edge_types_column_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_list_edge_types_column_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__edge_list_edge_types_column = Slot(uri=DEFAULT_.edge_list_edge_types_column, name="ensmallenRunConfig__edge_list_edge_types_column", curie=DEFAULT_.curie('edge_list_edge_types_column'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_list_edge_types_column, domain=None, range=Optional[str])

slots.ensmallenRunConfig__default_edge_type = Slot(uri=DEFAULT_.default_edge_type, name="ensmallenRunConfig__default_edge_type", curie=DEFAULT_.curie('default_edge_type'),
                   model_uri=DEFAULT_.ensmallenRunConfig__default_edge_type, domain=None, range=Optional[str])

slots.ensmallenRunConfig__weights_column_number = Slot(uri=DEFAULT_.weights_column_number, name="ensmallenRunConfig__weights_column_number", curie=DEFAULT_.curie('weights_column_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__weights_column_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__weights_column = Slot(uri=DEFAULT_.weights_column, name="ensmallenRunConfig__weights_column", curie=DEFAULT_.curie('weights_column'),
                   model_uri=DEFAULT_.ensmallenRunConfig__weights_column, domain=None, range=Optional[str])

slots.ensmallenRunConfig__default_weight = Slot(uri=DEFAULT_.default_weight, name="ensmallenRunConfig__default_weight", curie=DEFAULT_.curie('default_weight'),
                   model_uri=DEFAULT_.ensmallenRunConfig__default_weight, domain=None, range=Optional[float])

slots.ensmallenRunConfig__edge_ids_column = Slot(uri=DEFAULT_.edge_ids_column, name="ensmallenRunConfig__edge_ids_column", curie=DEFAULT_.curie('edge_ids_column'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_ids_column, domain=None, range=Optional[str])

slots.ensmallenRunConfig__edge_ids_column_number = Slot(uri=DEFAULT_.edge_ids_column_number, name="ensmallenRunConfig__edge_ids_column_number", curie=DEFAULT_.curie('edge_ids_column_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_ids_column_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__edge_list_numeric_edge_type_ids = Slot(uri=DEFAULT_.edge_list_numeric_edge_type_ids, name="ensmallenRunConfig__edge_list_numeric_edge_type_ids", curie=DEFAULT_.curie('edge_list_numeric_edge_type_ids'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_list_numeric_edge_type_ids, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__edge_list_numeric_node_ids = Slot(uri=DEFAULT_.edge_list_numeric_node_ids, name="ensmallenRunConfig__edge_list_numeric_node_ids", curie=DEFAULT_.curie('edge_list_numeric_node_ids'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_list_numeric_node_ids, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__skip_weights_if_unavailable = Slot(uri=DEFAULT_.skip_weights_if_unavailable, name="ensmallenRunConfig__skip_weights_if_unavailable", curie=DEFAULT_.curie('skip_weights_if_unavailable'),
                   model_uri=DEFAULT_.ensmallenRunConfig__skip_weights_if_unavailable, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__skip_edge_types_if_unavailable = Slot(uri=DEFAULT_.skip_edge_types_if_unavailable, name="ensmallenRunConfig__skip_edge_types_if_unavailable", curie=DEFAULT_.curie('skip_edge_types_if_unavailable'),
                   model_uri=DEFAULT_.ensmallenRunConfig__skip_edge_types_if_unavailable, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__edge_list_is_complete = Slot(uri=DEFAULT_.edge_list_is_complete, name="ensmallenRunConfig__edge_list_is_complete", curie=DEFAULT_.curie('edge_list_is_complete'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_list_is_complete, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__edge_list_may_contain_duplicates = Slot(uri=DEFAULT_.edge_list_may_contain_duplicates, name="ensmallenRunConfig__edge_list_may_contain_duplicates", curie=DEFAULT_.curie('edge_list_may_contain_duplicates'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_list_may_contain_duplicates, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__edge_list_is_sorted = Slot(uri=DEFAULT_.edge_list_is_sorted, name="ensmallenRunConfig__edge_list_is_sorted", curie=DEFAULT_.curie('edge_list_is_sorted'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_list_is_sorted, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__edge_list_is_correct = Slot(uri=DEFAULT_.edge_list_is_correct, name="ensmallenRunConfig__edge_list_is_correct", curie=DEFAULT_.curie('edge_list_is_correct'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_list_is_correct, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__edge_list_max_rows_number = Slot(uri=DEFAULT_.edge_list_max_rows_number, name="ensmallenRunConfig__edge_list_max_rows_number", curie=DEFAULT_.curie('edge_list_max_rows_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_list_max_rows_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__edge_list_comment_symbol = Slot(uri=DEFAULT_.edge_list_comment_symbol, name="ensmallenRunConfig__edge_list_comment_symbol", curie=DEFAULT_.curie('edge_list_comment_symbol'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edge_list_comment_symbol, domain=None, range=Optional[str])

slots.ensmallenRunConfig__edges_number = Slot(uri=DEFAULT_.edges_number, name="ensmallenRunConfig__edges_number", curie=DEFAULT_.curie('edges_number'),
                   model_uri=DEFAULT_.ensmallenRunConfig__edges_number, domain=None, range=Optional[int])

slots.ensmallenRunConfig__load_edge_list_in_parallel = Slot(uri=DEFAULT_.load_edge_list_in_parallel, name="ensmallenRunConfig__load_edge_list_in_parallel", curie=DEFAULT_.curie('load_edge_list_in_parallel'),
                   model_uri=DEFAULT_.ensmallenRunConfig__load_edge_list_in_parallel, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__verbose = Slot(uri=DEFAULT_.verbose, name="ensmallenRunConfig__verbose", curie=DEFAULT_.curie('verbose'),
                   model_uri=DEFAULT_.ensmallenRunConfig__verbose, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__may_have_singletons = Slot(uri=DEFAULT_.may_have_singletons, name="ensmallenRunConfig__may_have_singletons", curie=DEFAULT_.curie('may_have_singletons'),
                   model_uri=DEFAULT_.ensmallenRunConfig__may_have_singletons, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__may_have_singleton_with_selfloops = Slot(uri=DEFAULT_.may_have_singleton_with_selfloops, name="ensmallenRunConfig__may_have_singleton_with_selfloops", curie=DEFAULT_.curie('may_have_singleton_with_selfloops'),
                   model_uri=DEFAULT_.ensmallenRunConfig__may_have_singleton_with_selfloops, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__directed = Slot(uri=DEFAULT_.directed, name="ensmallenRunConfig__directed", curie=DEFAULT_.curie('directed'),
                   model_uri=DEFAULT_.ensmallenRunConfig__directed, domain=None, range=Optional[Union[bool, Bool]])

slots.ensmallenRunConfig__name = Slot(uri=DEFAULT_.name, name="ensmallenRunConfig__name", curie=DEFAULT_.curie('name'),
                   model_uri=DEFAULT_.ensmallenRunConfig__name, domain=None, range=Optional[str])